### ISSUE TITLE
How to disable stemcell image decompression for grootfs?

### ISSUE THREAD

**Issue by kayrus** [cppforlife/bosh-warden-cpi-release#18]
Initially I reported a [bug report](https://github.com/cloudfoundry/grootfs/issues/15) in grootfs project, but detailed debugging showed that it is a `bosh-warden-cpi-release` issue.

It looks like warden-cpi always [decompresses](https://github.com/cppforlife/bosh-warden-cpi-release/blob/cf1e4be1d4f556a9e1dbab38e0186f8f2e0fc09f/src/github.com/cppforlife/bosh-warden-cpi/stemcell/fs_importer.go#L60) a stemcell image.

I cannot create an instance because grootfs complain on directory structure. It expects to see a tar archive:

```
Creating VM with agent ID '{{eb2931fc-1e68-44ef-8492-876b7f01647f}}': Creating container: running image plugin create: invalid base image: directory provided instead of a tar file
```

How can I disable decompression feature?

**Comment by kayrus** [comment]
Fixed by setting the `ExpandStemcellTarball` to false.

**Comment by cagiti** [comment]
Was this fixed within a release or by specifying the above? If the above, how would I go about setting that property? Thanks

**Comment by kayrus** [comment]
```
- type: replace
  path: /instance_groups/name=bosh/properties/warden_cpi?
  value:
    host_ip: 10.254.50.4
    actions:
      expand_stemcell_tarball: false
    warden:
      connect_network: tcp
      connect_address: 127.0.0.1:7777
    agent: # todo remove once cpi dont know about these
      mbus: nats://nats:((nats_password))@10.254.50.4:4222
      blobstore:
        provider: dav
        options:
          endpoint: http://10.254.50.4:25250
          user: agent
          password: ((blobstore_agent_password))
```
